---
esphome:
  name: test-nuki

  libraries:
    - Preferences
    - https://github.com/h2zero/NimBLE-Arduino
    - Crc16
    - https://github.com/AzonInc/NukiBleEsp32#dev

esp32:
  framework:
    type: arduino
    version: 2.0.3
    platform_version: 5.3.0

packages:
  common: !include shared-config.yaml
